/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.trabalholistadetarefas.view;

import com.mycompany.trabalholistadetarefas.controller.TasksController;

/**
 *
 * @author JOAOPEDROBACKXAVIER
 */
public class Focus extends javax.swing.JFrame {

    /**
     * Creates new form focus
     */
    public Focus(String title,String description, String expire_date, String state) {
        initComponents();
        titleLabel.setText(title);
        descriptionLabel.setText(description);
        expireDateLabel.setText(expire_date);
        
        if("completed".equals(state)){
            stateButtom.setEnabled(true);
        }else if("pending".equals(state)){
            stateButtom.setEnabled(false);            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        expireDateLabel = new javax.swing.JLabel();
        editButtom = new javax.swing.JButton();
        deleteButtom = new javax.swing.JButton();
        stateButtom = new javax.swing.JCheckBox();
        okButtom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N

        titleLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titleLabel.setText("titulo");

        descriptionLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        descriptionLabel.setText("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");

        expireDateLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        expireDateLabel.setText("data de vencimento");

        editButtom.setText("edit");

        deleteButtom.setText("delete");
        deleteButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtomActionPerformed(evt);
            }
        });

        stateButtom.setText("state");

        okButtom.setText("ok");
        okButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(expireDateLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(descriptionLabel)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(editButtom)
                                    .addGap(18, 18, 18)
                                    .addComponent(deleteButtom)
                                    .addGap(34, 34, 34)
                                    .addComponent(stateButtom)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(okButtom)))
                            .addComponent(titleLabel))
                        .addContainerGap(125, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(titleLabel)
                .addGap(30, 30, 30)
                .addComponent(descriptionLabel)
                .addGap(18, 18, 18)
                .addComponent(expireDateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButtom)
                    .addComponent(editButtom)
                    .addComponent(stateButtom)
                    .addComponent(okButtom))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtomActionPerformed
        String title = titleLabel.getText();
        TasksController.deleteTask(title);
        new Tasks().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_deleteButtomActionPerformed

    private void okButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtomActionPerformed
        new Tasks().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_okButtomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButtom;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JButton editButtom;
    private javax.swing.JLabel expireDateLabel;
    private javax.swing.JButton okButtom;
    private javax.swing.JCheckBox stateButtom;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
